### ISSUE TITLE
您好 您能提供一个编译好的ipa文件吗

### ISSUE THREAD

**Issue by Fateliu** [Oliver0624/hin2n-ios#1]
是必须使用开发者账号编译的吗 还是可以编译好的ipa签名安装

**Comment by Oliver0624** [comment]
没有试过对编译好的程序进行签名。之前有网友拿了我编译的ipa文件自行签名，结果失败了，可能是因为他是个人用户，没有Network Extension的权限。

建议还是用Mac编译安装（必须要有开发者账号和Network Extension权限）。如果实在想尝试自行签名，你可以试试[这个网址](https://www.pgyer.com/RShr)
