### ISSUE TITLE
about DNS support

### ISSUE THREAD

**Issue by chen-hongbo** [Oliver0624/hin2n-ios#4]
1. 在设置界面里用域名作为supernode名称，ping 了有10个包，就断线ping不通，但是用IP地址作为supernode名称，是可以持续ping通的；
2. 在用IP地址做supernode 名称时，用浏览器访问的URL用如https://IP:port 可以正常访问，URL用域名访问失败。

QQ:706574875

**Comment by Oliver0624** [comment]
看不懂...可以的话直接用汉语吧。
